### ISSUE TITLE
百分比自适应正方形解决方案

### ISSUE THREAD

**Issue by l-ll** [l-ll/l-ll.github.io#6]
## 方法1

利用padding 百分比 基于父容器宽度这一特性来实现

``` html
<div class="parent">
  <div class="child"></div>
</div>
```

``` css
.parent {
  width: 200px;
  height: 200px;
  background: #000;
}
.child {
  background: #ddd;
  width: 50%;
}
.child::after {
  display: block;
  padding-top: 100%;
  content: '';
}
```
## 方法2

CSS3 calc()

``` css
.child3 {
  width: calc(50%);
  height: calc(50%);
  background: #ddd;
}
```

[这里](http://jsbin.com/tipoqudaga/edit?html,css,output)
